# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

use_frameworks! # LeanCloud Swift SDK can only be integrated as framework.

target 'NJSY' do
pod 'LeanCloud'
pod 'SnapKit', '~> 3.2.0'
end
