# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

use_frameworks! # LeanCloud Swift SDK can only be integrated as framework.

target 'NJSY' do
pod 'LeanCloud', '~> 10.1.0'
pod 'SnapKit', '~> 3.2.0'
pod 'EasyToast', '~> 2.0.2'
pod 'SwiftSocket'
pod 'Socket.IO-Client-Swift', '~> 12.1.2'
pod 'ReachabilitySwift', '~> 3'
pod 'HandyJSON', '~> 1.7.2'
end
